- platform: template
  sensors:
    kitchen_motion:
      friendly_name: "Kitchen Motion"
      device_class: motion
      value_template: "{{ is_state('input_boolean.kitchen_motion', 'on') }}"
    smoke_detector_garage_status:
      friendly_name: "Smoke - Garage Status"
      device_class: "smoke"
      value_template: >-
        {{ (is_state("sensor.smoke_detector_garage_alarm_level", "255") and is_state("sensor.smoke_detector_basement_alarm_type", "1")) or
            (is_state("sensor.smoke_detector_garage_alarm_level", "255") and is_state("sensor.smoke_detector_basement_alarm_type", "2")) }}

    smoke_detector_kitchen_status:
      friendly_name: "Smoke - Kitchen Status"
      device_class: "smoke"
      value_template: >-
        {{ (is_state("sensor.smoke_detector_kitchen_alarm_level", "255") and is_state("sensor.smoke_detector_main_floor_alarm_type", "1")) or
            (is_state("sensor.smoke_detector_kitchen_alarm_level", "255") and is_state("sensor.smoke_detector_main_floor_alarm_type", "2")) }}

    smoke_detector_upstairs_status:
      friendly_name: "Smoke - Upstairs Status"
      device_class: "smoke"
      value_template: >-
        {{ (is_state("sensor.smoke_detector_upstairs_alarm_level", "255") and is_state("sensor.smoke_detector_upstairs_alarm_type", "1")) or
            (is_state("sensor.smoke_detector_upstairs_alarm_level", "255") and is_state("sensor.smoke_detector_upstairs_alarm_type", "2")) }}

    smoke_detector_play_room_status:
      friendly_name: "Smoke - Play Room Status"
      device_class: "smoke"
      value_template: >-
        {{ (is_state("sensor.smoke_detector_play_room_alarm_level", "255") and is_state("sensor.smoke_detector_basement_alarm_type", "1")) or
            (is_state("sensor.smoke_detector_play_room_alarm_level", "255") and is_state("sensor.smoke_detector_basement_alarm_type", "2")) }}
