- platform: template
  covers:
    big_bedroom_curtains:
      friendly_name: "Big Bedroom Curtains"
      position_template: "{{ states('sensor.big_bedroom_curtain_position') }}"
      open_cover:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot_big_bedroom_deviceId
          command: "turnOn"
          parameter: ""
      close_cover:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot_big_bedroom_deviceId
          command: "turnOff"
          parameter: ""
      stop_cover:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot_big_bedroom_deviceId
          command: "turnOff"
          parameter: ""
      set_cover_position:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot_big_bedroom_deviceId
          command: "setPosition"
          parameter: "0,ff,{{position}}"
    small_bedroom_curtains:
      friendly_name: "Small Bedroom Curtains"
      position_template: "{{ states('sensor.small_bedroom_curtain_position') }}"
      open_cover:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot_small_bedroom_deviceId
          command: "turnOn"
          parameter: ""
      close_cover:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot_small_bedroom_deviceId
          command: "turnOff"
          parameter: ""
      stop_cover:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot_small_bedroom_deviceId
          command: "turnOff"
          parameter: ""
      set_cover_position:
        service: rest_command.switchbot_device_command
        data:
          deviceId: !secret switchbot_small_bedroom_deviceId
          command: "setPosition"
          parameter: "0,ff,{{position}}"