- platform: switch
  name: Guest Room Lamp
  entity_id: switch.guest_room_lamp

- platform: switch
  name: Kitchen Spotlights
  entity_id: switch.kitchen_spotlights

- platform: switch
  name: Backyard Lights
  entity_id: switch.backyard_lights

- platform: switch
  name: Vanity Lights
  entity_id: switch.vanity_lights

- platform: switch
  name: Bedroom Lamps
  entity_id: switch.bedroom_lamps

- platform: switch
  name: Deck Lights
  entity_id: switch.deck_lights

- platform: switch
  name: Dining Room Chandelier
  entity_id: switch.dining_room_chandelier

- platform: switch
  name: Driveway Lights
  entity_id: switch.driveway_lights

- platform: switch
  name: Entry Lamps
  entity_id: switch.entry_lamps

- platform: switch
  name: Gable Lights
  entity_id: switch.gable_lights

- platform: switch
  name: Garage Lights
  entity_id: switch.garage_lights

- platform: switch
  name: Green Light
  entity_id: switch.green_light

- platform: switch
  name: Shop Driveway Lights
  entity_id: switch.shop_driveway_lights
  
- platform: switch
  name: Kitchen Cabinet Lights
  entity_id: switch.kitchen_cabinet_lights

- platform: group
  name: bathroom lights
  unique_id: '393454292'
  entities:
    - light.vanity_lights
    - light.shower_flood_light
    - light.toilet_flood_light

- platform: group
  name: Kitchen Counter Lights
  unique_id: '3444893'
  entities:
    - light.kitchen_light_strip
    - light.kitchen_cabinet_lights
    - light.kitchen_edge_lights

- platform: group
  name: Kitchen Lights
  unique_id: kitchenlights
  entities:
    - light.kitchen_hanging_lights
    - light.kitchen_counter_lights
    - light.kitchen_spotlights
    - light.nook_lights
    - light.kitchen_edge_lights

- platform: group
  name: Downstairs Lights
  unique_id: downstairslights
  entities:
    - light.entry_lamps
    - light.desk_lamp
    - light.downstairs_sconces
    - light.entry_chandelier
    - light.fireplace_lights
    - light.high_floodlights
    - light.kitchen_hanging_lights
    - light.nook_lights
    - light.play_room_ceiling_lights
    - light.dining_room_chandelier
    - light.entry_lamps
    - light.kitchen_counter_lights
    - light.kitchen_spotlights
    - light.kitchen_edge_lights
    - light.tv_room_ceiling_light_1
    - light.tv_room_ceiling_light_2

- platform: group
  name: All Lights
  unique_id: alllights
  entities:
    - light.kitchen_edge_lights
    - light.bathroom_lights
    - light.desk_lamp
    - light.gable_lights
    - light.garage_lights
    - light.tv_room_ceiling_light_1
    - light.tv_room_ceiling_light_2
    - light.shop_driveway_lights
    - light.bedroom_lamps
    - light.driveway_lights
    - light.entry_lamps
    - light.downstairs_sconces
    - light.upstairs_sconces
    - light.bedroom_sconces
    - light.entry_chandelier
    - light.fireplace_lights
    - light.high_floodlights
    - light.kitchen_hanging_lights
    - light.nook_lights
    - light.play_room_ceiling_lights
    - light.dining_room_chandelier
    - light.entry_lamps
    - light.kitchen_spotlights
    - light.kitchen_counter_lights
